# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andrew Wilson
title: Software Engineer ⁂ Power Plant Systems Expert
email: andrew.j.wilson2479@gmail.com
website: aldonadi.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  aldonadi
linkedin_username: andrew-wilson-6b469b1a9
youtube_username: "@AndrewWilson-i2k"

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Andrew Wilson and I am a software engineer with over 10 years of experience in the military and civilian power plant sector. I am infinitely curious and love understanding and solving problems with software.

  Languages I am skilled in: <mark>Python</mark>, <mark>Java</mark>, <mark>Kotlin</mark>, <mark>Ruby</mark>, and <mark>Visual Basic</mark>.

  Technologies and frameworks: <mark>Android</mark>, <mark>Jetpack Compose</mark>, and <mark>Angular</mark>. 

content:
  - title: Self Assessment
    layout: text
    content: |
      > Your professional self-assessment. While you complete this last in the course, it should be the first thing presented in your ePortfolio. The self-assessment will function as a holistic introduction to you, your skills that can be quantifiably supported with your completed enhancements of the artifacts, and your ePortfolio.
      
      > For your ePortfolio, you will write a professional self-assessment. In it, you will reflect on the capstone and your experience in the Computer Science program. Your professional self-assessment will serve as the formal introduction to your portfolio. You will add it to the beginning of your portfolio for your final submission in Module Seven.
      
      > Employers often interview a number of technically qualified candidates, so you should try to emphasize aspects of your ePortfolio that set you apart and quantifiably illustrate your competence and employability. In addition, the professional self-assessment is an opportunity to showcase your superior computer science knowledge, skills, and expertise. Be sure that your professional self-assessment is well-organized and thoughtful and that it effectively communicates your strengths in the field of computer science. The self-assessment might be a great first draft of a cover letter and useful as you apply for jobs with your new degree. Take advantage of your instructor’s feedback for this reason.

      - Discuss how completing your coursework throughout the program and developing the ePortfolio has helped you showcase your strengths, shape your professional goals and values, and prepare to enter or become more employable in the computer science field.
        1. Use specific examples from your program and include examples outside of the artifacts included in your ePortfolio.
        2. Address the following topics: collaborating in a team environment, communicating with stakeholders, data structures and algorithms, software engineering and database, and security. This section should function as an overall introduction to your skills, not a discussion of the artifacts.

      - Summarize and introduce how your artifacts fit together and inform the portfolio as a whole.
        1. This summary will help demonstrate the full range of your computer science talents and abilities.
        2. This section should introduce your audience to the technical artifacts that follow the professional self-assessment.



  - title: Selected Artifacts 
    layout: list

    content:
      - layout: left
        title: Software Engineering and Design
        sub_title: Enhancement One
        quote: >
          Garden Tracking App UI/Flow Wireframe and Implementation
        description: |
          
          I had designed a wireframe in LucidChart for my theoretical garden tracking app, specifically the workflow of logging the watering of a garden crops. You can see [the artifact before any enhancements here.](/assets/garden-app-ui-wireframe.pdf).

          I chose this as an artifact to enhance because it demonstrates the ability to set up and configure complex development environments (Android Studio) and utilize software development best practices and modern frameworks to create a functional application. To be more specific, I implemented this workflow UI using Android's Jetpack Compose library. This is a _reactive UI_ which revolves around data streams (or "flows") for continuous live updating. Implementing this workflow required me to write a large amount of boilerplate code and component wiring between `ViewModel` objects, `@Composable` functions, `Compose Navigation` controller objects, and of course tight integration with the Android OS environment. I had to resort constantly to the [official Android documentation](https://developer.android.com/develop/ui/compose/documentation) along with guides and videos. I found the official documentation to be lacking in several areas which required me to dig into existing open source applications that use Compose to see how things are done. The enhancements breathed life into the static wireframe.

          <img src="images/gardentracker-showcase.gif" alt="Watering workflow showcase" height="600"/>

          The full code for the implemented Garden Tracker application can be [found on GitHub](https://github.com/aldonadi/GardenTracker).

          Specific code examples: Here is the code for the app's [summary screen UI](https://github.com/aldonadi/GardenTracker/blob/master/app/src/main/java/com/cs499/gardentracker/ui/screens/summary/SummaryScreen.kt) and [ViewModel](https://github.com/aldonadi/GardenTracker/blob/master/app/src/main/java/com/cs499/gardentracker/ui/screens/summary/SummaryViewModel.kt).

          ## Reflection
          
          I learned quite a bit standing up this application and the boilerplate necessary for Compose UI. First was becoming accustomed with thinking in _reactive UI_ and functional patterns, which is very different from object-oriented UI design. As I stated above, deficiencies in the documentation (mostly stemming from out-of-date information) led me down numerous dead-ends. However, I have gained a wealth of knowledge and experience in how to design and implement composable UIs in the MVVM architecture.

          While there are many points of refinement I have not yet attended to in my app, I believe that I have successfully demonstrated the outcomes I set out to demonstrate, with comment. Specifically, I believe I successfully **employed strategies for building collaborative environments for diverse audiences** through the use of my user interviews for eliciting requirements. I also **designed, developed, and delivered professional communications** through my UI design and comments throughout the code.

          However, I believe I have _incompletely_ demonstrated **well-founded and innovative techniques for implementing solutions** due to one very large defect in my implementation. This is that I am NOT taking advantage of streaming `Flow` objects for anything except the passing of data from my ViewModels to my composable functions. This means that the chain of data from database, to DAO, to repository, to ViewModel can become stale without manually refreshing. I did not catch on to this flaw until late in the course and I have not had time to fix it (yet).

          ## Artifact materials

          - Before enhancement: [Watering workflow wireframe](/assets/garden-app-ui-wireframe.pdf)
          - After enhancement: [Garden Tracker App](https://github.com/aldonadi/GardenTracker)


      - layout: left
        title: Algorithms and Data Structures
        sub_title: Enhancement Two
        quote: >
          User Interviews, Paper Prototypes, and Data Organization
        description: |
          I had previously interviewed three potential users to elicit requirements and obtain feedback on concept versions of my garden app. I used paper prototypes of screens to assist the interviewees in navigating various workflows. The [data I obtained from these interviews](/assets/interview-records.pdf) helped me to construct the data structures and algorithms necessary to organize various kinds of data and relationships that I would need to implement in the app, as well as the operations I would need to perform on them.

          I chose this as an artifact since it showcases my abilities to convert functional and business requirements into computable representations by selecting appropriate data types and algorithms for best performance and usability.

          For example, I organized garden data into [`PlotEntity`](https://github.com/aldonadi/GardenTracker/blob/master/app/src/main/java/com/cs499/gardentracker/data/plot/PlotEntity.kt) objects which can contain one or more [`CropEntity`](https://github.com/aldonadi/GardenTracker/blob/master/app/src/main/java/com/cs499/gardentracker/data/crop/CropEntity.kt) objects. These are essentially `struct`s that I collect into `List` containers for transferring around the program. As another example, on the Watering List screen ViewModel, I [create a map of `plotId`s to plot names](https://github.com/aldonadi/GardenTracker/blob/bd9ecdc2615f7c32bd03df20a8b406110266b470/app/src/main/java/com/cs499/gardentracker/ui/screens/watering/WateringListViewModel.kt#L78) for creating the plot name header rows that each plot's crop is displayed beneath.

          ## Reflection

          I had never seen Kotlin code before starting this course, I had to quickly get familiar with Kotlin syntax and idiosyncrasies, such as the concept of `data class` and the specific functional algorithm method names that can be used on collections. I refined my ability to think in functional, rather than procedural, terms. Additionally, I went through several iterations to arrive at the set of operations I perform on my data in the ViewModel for performance and memory usage reasons. At first I collected all data from the database as potentially huge lists of objects, but I was able to refine that approach to be more selective and performant. However, one large defect that remains is that I am not making effective use of threads and coroutines to minimize latency. For example, I have several examples of calling [`async` and `await` on the same line](https://github.com/aldonadi/GardenTracker/blob/bd9ecdc2615f7c32bd03df20a8b406110266b470/app/src/main/java/com/cs499/gardentracker/ui/screens/summary/SummaryViewModel.kt#L74), effectively neutering any coroutine advantages.

          I believe I successfully demonstrated the three outcomes I set out to, again with a comment. I **designed, developed, and delivered professional-quality communications** largely through my code comments and this narrative. I **designed and evaluated computing solutions solving problems using algorithmic principles** by  my selection and usage of different data structures and filtering algorithms. I believe I have _partially_ demonstrated **the ability to use well-founded and innovative techniques**, due to my imperfect utilization of multiprocessing.

          ## Artifact materials

          - Before enhancement: [User Interview records](/assets/interview-records.pdf)
          - After enhancement: [Garden Tracker App](https://github.com/aldonadi/GardenTracker)

      - layout: left
        title: Database 
        sub_title: Enhancement Three
        link: "/aldonadi.github.io/assets/interview-records.pdf"
        link_text: [PDF link]
        quote: >
          Interviewing potential users along with paper prototypes of screens helped me elicit the data structures and algorithms necessary to organize and work with the various kinds of data that I would need to implement in the app.
        description: |
          ## Before Enhancement

          Description before enhancement.

          ## After Enhancement

          Description after enhancement.



  - title: Code Review
    layout: list
    content:
      - layout: top-middle
        quote: >
          Critically examining a previous Android app and pointing out opportunities for enhancement.
        description: |
          Here is the video of the <b>code</b> review:

          <iframe width="560" height="315" src="https://www.youtube.com/embed/17OiQtpx3Wo?si=qo2_y0UXNl3DC-Xg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>



#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: InvyTrakr
#        link: github.com/aldonadi/InvyTrakr
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        #quote: >
#        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I wrote this inventory tracking app during my Mobile Architecture class at SNHU. During its development I learned about Android OS architecture, app lifecycle management, the Room database abstraction layer, and XML UI layouts.
#
#  #- title: Experience # Title for the section
#  #  layout: list # Type of content section (list/text)
#  #  content:
#  #    - layout: left
#  #      title: The Boring Company
#  #      link: boringcompany.com
#  #      # link_text: boringcompany.com
#  #      sub_title: Senior Network System Administrator
#  #      caption: November 2017 - Present
#  #      quote: >
#  #        Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#  #      description: | # this will include new lines to allow paragraphs
#  #          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
#
#  - title: Education # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: Southern New Hampshire University (SNHU)
#        caption: 2022 - 2026
#        sub_title: BSc Computer Science - Software Engineering
#        quote: >
#          Beginning in 1932 as a 2-room business school, SNHU is now a thriving online and on-campus university with 200 programs and 200,000 online students.
#        description: | # this will include new lines to allow paragraphs
#          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
#
#          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
#
#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      I have 
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image  
#      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
