# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andrew Wilson
title: Software Engineer ⁂ Power Plant Systems Expert
email: andrew.j.wilson2479@gmail.com
website: aldonadi.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  aldonadi
linkedin_username: andrew-wilson-6b469b1a9
youtube_username: "@AndrewWilson-i2k"

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Andrew Wilson and I am a software engineer with over 10 years of experience in the military and civilian power plant sector. I am infinitely curious and love understanding and solving problems with software.

  Languages I am skilled in: <mark>Python</mark>, <mark>Java</mark>, <mark>Kotlin</mark>, <mark>Ruby</mark>, and <mark>Visual Basic</mark>.

  Technologies and frameworks: <mark>Android</mark>, <mark>Jetpack Compose</mark>, and <mark>Angular</mark>. 

content:
  - title: Professional Self-Assessment
    layout: text
    content: |
        My experience over the last 3 years in SNHU's Computer Science course has been one of challenges and rewarding growth. I have been exposed to many, many areas of this field that I would not have otherwise, such as reverse engineering, embedded systems programming, full-stack development, user interface design, and of course a TON of writing. I have developed skills in communicating technical concepts and concerns to audiences spanning from the C-suite, to developer peers, potential customers, and to users. For example, I have written a security policy document translating technical security requirements into language that business-minded managers can understand. I have crafted user interview scripts and engaged in live interviews with real potential stakeholders and users to elicit requirements and feedback for an upcoming program. I have built up a corpus of programming artifacts that both showcase my skills and pinpoint my developmental progress at various stages throughout my journey. I have developed a text-adventure program in Python, an Angular app with Express backend server, numerous MongoDB databases, and even reverse engineered legacy executables to enable interoperability with new systems. I have analyzed code and repositories for security vulnerabilities and produced actionable reports with recommendations for developer teams and implemented bug fixes in my own code. I have engaged with peer students and professorial staff throughout my studies, participating in group discussions and critical but thoughtful examinations. This has required me to communicate effectively to diverse audiences about difficult topics without the distraction of being offensive.

        During this last capstone course, I set out to convert a series of user interviews and wireframes from a previous course into a working Android app for tracking garden maintenance (like watering and planting) using modern approaches and frameworks. This required me to learn Kotlin, Jetpack Compose, Compose Navigation, and a slew of Android OS integrations that must accompany these.

        To showcase this, I have chosen three specific artifacts for enhancement. Each artifact is intended to demonstrate a key ability in the areas of **Software Engineering and Development**, **Algorithms and Data Structures**, and **Databases**. My artifacts are as follows:

        - Software Engineering and Development:
          - Before enhancement: a wireframe diagram illustrating a workflow of logging the watering of a garden plot.
          - After enhancement: the completed source code for the app which implements this and a video screenshot showing the process.

        - Algorithms and Data Structures:
          - Before enhancement: the collections of notes from interviews that I conducted with three real potential users of this garden app, with elicited requirements.
          - After enhancement: the completed source code, and particular selected portions of code linked to in the description.

        - Databases:
          - Before enhancement: the overall concept document I produced after the interviews and wireframe discussing the required data for the app.
          - After enhancement: the completed source code, with particular selected portions of code linked to in the description.


  - title: Selected Artifacts 
    layout: list

    content:
      - layout: left
        title: Software Engineering and Design
        sub_title: Enhancement One
        quote: >
          Garden Tracking App UI/Flow Wireframe and Implementation
        description: |
          
          I had designed a wireframe in LucidChart for my theoretical garden tracking app, specifically the workflow of logging the watering of a garden crops. You can see [the artifact before any enhancements here.](/assets/garden-app-ui-wireframe.pdf).

          I chose this as an artifact to enhance because it demonstrates the ability to set up and configure complex development environments (Android Studio) and utilize software development best practices and modern frameworks to create a functional application. To be more specific, I implemented this workflow UI using Android's Jetpack Compose library. This is a _reactive UI_ which revolves around data streams (or "flows") for continuous live updating. Implementing this workflow required me to write a large amount of boilerplate code and component wiring between `ViewModel` objects, `@Composable` functions, `Compose Navigation` controller objects, and of course tight integration with the Android OS environment. I had to resort constantly to the [official Android documentation](https://developer.android.com/develop/ui/compose/documentation) along with guides and videos. I found the official documentation to be lacking in several areas which required me to dig into existing open source applications that use Compose to see how things are done. The enhancements breathed life into the static wireframe.

          <img src="images/gardentracker-showcase.gif" alt="Watering workflow showcase" height="600"/>

          The full code for the implemented Garden Tracker application can be [found on GitHub](https://github.com/aldonadi/GardenTracker).

          Specific code examples: Here is the code for the app's [summary screen UI](https://github.com/aldonadi/GardenTracker/blob/master/app/src/main/java/com/cs499/gardentracker/ui/screens/summary/SummaryScreen.kt) and [ViewModel](https://github.com/aldonadi/GardenTracker/blob/master/app/src/main/java/com/cs499/gardentracker/ui/screens/summary/SummaryViewModel.kt).

          ## Reflection
          
          I learned quite a bit standing up this application and the boilerplate necessary for Compose UI. First was becoming accustomed with thinking in _reactive UI_ and functional patterns, which is very different from object-oriented UI design. As I stated above, deficiencies in the documentation (mostly stemming from out-of-date information) led me down numerous dead-ends. However, I have gained a wealth of knowledge and experience in how to design and implement composable UIs in the MVVM architecture.

          I believe that I have, overall, successfully demonstrated the outcomes I set out to demonstrate. However, there are many points of refinement I have not yet attended to in my app. Specifically, I believe I successfully **employed strategies for building collaborative environments for diverse audiences** through the use of my user interviews for eliciting requirements. I also **designed, developed, and delivered professional communications** through my UI design and comments throughout the code.

          However, I believe I have _incompletely_ demonstrated **well-founded and innovative techniques for implementing solutions** due to one very large defect in my implementation. This is that I am NOT taking advantage of streaming `Flow` objects for anything except the passing of data from my ViewModels to my composable functions. This means that the chain of data from database, to DAO, to repository, to ViewModel can become stale without manually refreshing. I did not catch on to this flaw until late in the course and I have not had time to fix it (yet).

          ## Artifact materials

          - Before enhancement: [Watering workflow wireframe](/assets/garden-app-ui-wireframe.pdf)
          - After enhancement: [Garden Tracker App](https://github.com/aldonadi/GardenTracker)
          - Narrative: [Milestone Two](/assets/3-2-milestone-two-narrative.pdf)


      - layout: left
        title: Algorithms and Data Structures
        sub_title: Enhancement Two
        quote: >
          User Interviews, Paper Prototypes, and Data Organization
        description: |
          I had previously interviewed three potential users to elicit requirements and obtain feedback on concept versions of my garden app. I used paper prototypes of screens to assist the interviewees in navigating various workflows. The [data I obtained from these interviews](/assets/interview-records.pdf) helped me to construct the data structures and algorithms necessary to organize various kinds of data and relationships that I would need to implement in the app, as well as the operations I would need to perform on them.

          I chose this as an artifact since it showcases my abilities to convert functional and business requirements into computable representations by selecting appropriate data types and algorithms for best performance and usability.

          For example, I organized garden data into [`PlotEntity`](https://github.com/aldonadi/GardenTracker/blob/master/app/src/main/java/com/cs499/gardentracker/data/plot/PlotEntity.kt) objects which can contain one or more [`CropEntity`](https://github.com/aldonadi/GardenTracker/blob/master/app/src/main/java/com/cs499/gardentracker/data/crop/CropEntity.kt) objects. These are essentially `struct`s that I collect into `List` containers for transferring around the program. As another example, on the Watering List screen ViewModel, I [create a map of `plotId`s to plot names](https://github.com/aldonadi/GardenTracker/blob/bd9ecdc2615f7c32bd03df20a8b406110266b470/app/src/main/java/com/cs499/gardentracker/ui/screens/watering/WateringListViewModel.kt#L78) for creating the plot name header rows that each plot's crop is displayed beneath.

          ## Reflection

          I had never seen Kotlin code before starting this course, I had to quickly get familiar with Kotlin syntax and idiosyncrasies, such as the concept of `data class` and the specific functional algorithm method names that can be used on collections. I refined my ability to think in functional, rather than procedural, terms. Additionally, I went through several iterations to arrive at the set of operations I perform on my data in the ViewModel for performance and memory usage reasons. At first I collected all data from the database as potentially huge lists of objects, but I was able to refine that approach to be more selective and performant. However, one large defect that remains is that I am not making effective use of threads and coroutines to minimize latency. For example, I have several examples of calling [`async` and `await` on the same line](https://github.com/aldonadi/GardenTracker/blob/bd9ecdc2615f7c32bd03df20a8b406110266b470/app/src/main/java/com/cs499/gardentracker/ui/screens/summary/SummaryViewModel.kt#L74), effectively neutering any coroutine advantages.

          I believe I successfully demonstrated the three outcomes I set out to, again with a comment. I **designed, developed, and delivered professional-quality communications** largely through my code comments and this narrative. I **designed and evaluated computing solutions solving problems using algorithmic principles** by  my selection and usage of different data structures and filtering algorithms. I believe I have _partially_ demonstrated **the ability to use well-founded and innovative techniques**, due to my imperfect utilization of multiprocessing.

          ## Artifact materials

          - Before enhancement: [User Interview records](/assets/interview-records.pdf)
          - After enhancement: [Garden Tracker App](https://github.com/aldonadi/GardenTracker)
          - Narrative: [Milestone Three](/assets/4-2-milestone-two-narrative.pdf)

      - layout: left
        title: Database 
        sub_title: Enhancement Three
        quote: >
          Converting Business Objects and Relationships into Database Primitives
        description: |


          In this artifact milestone, I added Android’s Room persistence library and implemented the necessary classes and annotations for two Data Access Objects (DAOs), one for `PlotEntity` and one for `CropEntity`. I created a [database class](https://github.com/aldonadi/GardenTracker/blob/bd9ecdc2615f7c32bd03df20a8b406110266b470/app/src/main/java/com/cs499/gardentracker/db/GardenTrackerDatabase.kt) and added the necessary boilerplate to my [`AppContainer`](https://github.com/aldonadi/GardenTracker/blob/bd9ecdc2615f7c32bd03df20a8b406110266b470/app/src/main/java/com/cs499/gardentracker/data/AppContainerImpl.kt) class to create the Room database from a seed sqlite3 shipped in the app’s assets directory, and hand-inserted several sample records.

          I developed and implemented a database schema for [Crops](https://github.com/aldonadi/GardenTracker/blob/bd9ecdc2615f7c32bd03df20a8b406110266b470/app/src/main/java/com/cs499/gardentracker/data/crop/CropEntity.kt) and [Plots](https://github.com/aldonadi/GardenTracker/blob/bd9ecdc2615f7c32bd03df20a8b406110266b470/app/src/main/java/com/cs499/gardentracker/data/plot/PlotEntity.kt). These include establishing primary keys for each table, adding constraints for which fields must not be null, adding indexes for several fields I expect to be accessed frequently, and established a foreign key constraint (and deletion propagation policy) for a one-to-many relationship between PlotEntity and CropEntity. I was careful to maintain the schema so far in fifth normal form, by separating independent facts into different tables, for example separating Crops from their Watering and FertilizingRecords. I also began implementing much more thorough unit testing, specifically on the CropDao class.

          ## Reflection

          While I feel that I have demonstrated the outcomes I set out to for this artifact, there is still much more to improve for my final project. For example, I have not yet converted the Watering, Fertilizing, Harvesting, or JournalRecord repositories to sqlite3-backed Room DAO yet. I have planned out the schema, but have not yet implemented the DAO interfaces and annotations yet in the Kotlin code itself.

          Doing this artifact enhancement has been more enjoyable and faster than the previous ones. By this point I had begun to grow accustomed with reading and writing Kotlin code with its eccentricities. I have more completely wrapped my mind around the Android Jetpack Compose architecture, and feel that I am starting to get the hang of reactive-based data flow and UI architecture. Unfortunately, I am still finding the official Android documentation for Compose, Compose Navigation, and Room to be confusing, out of date, and generally less than fully helpful. The best help I have found comes from copying parts of the documentation into an LLM and then challenging it with my questions, then trying to explain the concepts back to it in my own words while asking for its critiques.

          I, once again, assess that I have successfully demonstrated the outcomes set forth in my initial plan, but not to 100% satisfaction. Specifically, I have shown the ability to **use well-founded and innovative techniques** for database systems by implementing multiple data entities into table schemas, complete with key constraints and indices. On the other hand, I have only implemented some of my business objects to database persistence, therefore this is incomplete.

          I have also demonstrated **a security mindset that anticipates adversarial exploits** by utilizing the Room library which provides safety against SQL injection attacks. However, due to the limited, single-user, serverless nature of my application, my app operates in an admittedly limited threat environment.

          ## Artifact materials

          - Before enhancement: [App Concept Overview document](/assets/garden-app-concept-overview.pdf)
          - After enhancement: [Garden Tracker App, Database](https://github.com/aldonadi/GardenTracker/tree/bd9ecdc2615f7c32bd03df20a8b406110266b470/app/src/main/java/com/cs499/gardentracker/db)
          - Narrative: [Milestone Four](/assets/5-2-milestone-four-narrative.pdf)


  - title: Code Review
    layout: list
    content:
      - layout: top-middle
        quote: >
          Critically examining a previous Android app and pointing out opportunities for enhancement.
        description: |
          Here is the video of the <b>code</b> review:

          <iframe width="560" height="315" src="https://www.youtube.com/embed/17OiQtpx3Wo?si=qo2_y0UXNl3DC-Xg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


  # - title: AI Assistance Disclaimer
  #   layout: text
  #    content: |
  #
  #    I used LLMs to ask questions about code and documentation to help enhance my understanding and root out confusion. I used primarily gemma4:26b and gpt-oss:20b on a local server for this. I did not directly incorporate any code samples from any GenAI output into my application code.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
